repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use latest stable version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1  # Use latest version
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--remove-unused-variables","--in-place", "--recursive"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
