# Generated by Django 5.1.7 on 2025-03-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip",
                to="booking.booking",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Trip Planning"),
                    ("ongoing", "Ongoing"),
                    ("halt", "Halt / Cancelled"),
                    ("partially-completed", "Partially Completed"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="planning",
                help_text="This status is just for a reference and status should be dependent on corresponding Trips.",
                max_length=30,
            ),
        ),
    ]
